# Generated by Django 3.1.4 on 2020-12-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='gebre',
            new_name='genre',
        ),
    ]
